config:
    use_colors: True 
    printer_width: 120
    send_anonymous_usage_stats: False

astro-dbt-example-db:
  outputs:
    dev:
      type: postgres
      threads: 10
      keepalives_idle: 0
      host: "172.31.96.1"
      port: 5432
      user: "postgres"
      pass: "admin"
      dbname: dwh
      schema: dwh
  target: dev