version: 2

models:
  - name: dim_date
    description: Date dimension
    columns:
      - name: date_pk
        description: Lorem Ipsum
        tests:
          - unique
          - not_null
      - name: year
        description: Lorem Ipsum
        tests:
          - not_null
      - name: month
        description: Lorem Ipsum
        tests:
          - not_null
      - name: month_name
        description: Lorem Ipsum
        tests:
          - not_null
      - name: day_of_month
        description: Lorem Ipsum
        tests:
          - not_null
      - name: day_of_year
        description: Lorem Ipsum
        tests:
          - not_null
      - name: week_day_name
        description: Lorem Ipsum
        tests:
          - not_null
      - name: week
        description: Lorem Ipsum
        tests:
          - not_null
      - name: fmt_datum
        description: Lorem Ipsum
        tests:
          - not_null
      - name: quarter
        description: Lorem Ipsum
        tests:
          - not_null
      - name: year_quarter
        description: Lorem Ipsum
        tests:
          - not_null
      - name: year_month
        description: Lorem Ipsum
        tests:
          - not_null
      - name: year_week
        description: Lorem Ipsum
        tests:
          - not_null
      - name: month_start
        description: Lorem Ipsum
        tests:
          - not_null
      - name: month_end
        description: Lorem Ipsum
        tests:
          - not_null

  - name: dim_time
    description: Date dimension
    columns:
      - name: time_pk
        description: Lorem Ipsum
        tests:
          - unique
          - not_null
      - name: time_of_day
        description: Lorem Ipsum
        tests:
          - not_null
      - name: hour
        description: Lorem Ipsum
        tests:
          - not_null
      - name: minute
        description: Lorem Ipsum
        tests:
          - not_null
      - name: daytime_name
        description: Lorem Ipsum
        tests:
          - not_null
      - name: day_night
        description: Lorem Ipsum
        tests:
          - not_null

  - name: customer_snapshot
    description: Customer dimension
    columns:
      - name: customer_id
        description: Lorem Ipsum 
        config:
          type: varchar(50)
          primary_key: true
      - name: customer_name
        description: Lorem Ipsum
      - name: street
        description: Lorem Ipsum
      - name: city
        description: Lorem Ipsum
      - name: updated_dtm
        description: Lorem Ipsum
      - name: dbt_valid_from
        description: Lorem Ipsum
      - name: dbt_valid_to
        description: Lorem Ipsum
      - name: dbt_updated_at
        description: Lorem Ipsum
      - name: dbt_scd_id
        description: Lorem Ipsum

  - name: product_snapshot
    description: Product dimension
    columns:
      - name: product_id
        description: Lorem Ipsum
        config:
          type: int
          primary_key: true
      - name: product_name
        description: Lorem Ipsum
      - name: supplier_id
        description: Lorem Ipsum
      - name: producttype_id
        description: Lorem Ipsum
      - name: updated_dtm
        description: Lorem Ipsum
      - name: dbt_valid_from
        description: Lorem Ipsum
      - name: dbt_valid_to
        description: Lorem Ipsum
      - name: dbt_updated_at
        description: Lorem Ipsum
      - name: dbt_scd_id
        description: Lorem Ipsum

  - name: fact_orderline
    description: Order Facts
    columns:
      - name: order_fact_surrogate_key
        tests:
          - not_null
          - unique
      - name: order_date_key
        description: Lorem Ipsum
        tests:
          - not_null
      - name: time_key
        description: Lorem Ipsum
        tests:
          - not_null
      - name: product_key
        description: Lorem Ipsum
        tests:
          - not_null
      - name: customer_key
        description: Lorem Ipsum
        tests:
          - not_null
      - name: order_id
        description: Lorem Ipsum
        tests:
          - not_null
      - name: orderline_id
        description: Lorem Ipsum
        tests:
          - not_null
      - name: quantity
        description: Lorem Ipsum
        tests:
          - not_null
      - name: price
        description: Lorem Ipsum
        tests:
          - not_null
